### ISSUE TITLE
some little question

### ISSUE THREAD

**Issue by zhtrb** [duytai/sNeu#2]
1.What's the function of Hash_table.c?
2.‘$(CC) -c hash_table.c -o build/hash_table.o‘ 
It's a line from rust_instrument.sh. When I run this file in my machine, I always get an error message 
"./rust_instrument.sh: line 7: CC: command not found
./rust_instrument.sh: line 7: -c: command not found"
So I just wonder what compiler do you use? I think it could help me solve this problem.

**Comment by duytai** [comment]
@zhtrb I use it to store branch distances. However, this feature has not finished yet. 
CC is a path to your c compiler. You may add the following line at the beginning of rust_instrument.sh to make it work
```bash
CC="path-to-your-compiler" 
```
