### ISSUE TITLE
running problem.

### ISSUE THREAD

**Issue by zhtrb** [duytai/sNeu#4]
When I run step 4, there are crash like this:
~$ cd sNeu && ./fuzz_me coverage && ./fuzz_me nn
Traceback (most recent call last):
  File "./fuzz_me", line 28, in <module>
    coverage.count()
  File "/home/zht/sNeu/coverage.py", line 55, in count
    assert self.stats["shape"][0] > 0
AssertionError
have you ever met such thing?

**Comment by duytai** [comment]
@zhtrb sorry. I miss a step
```
AFL_DIR="$(pwd)/AFL/"
DEMO_DIR="$(pwd)/afl-demo/"

cd $DEMO_DIR
$AFL_DIR/afl-fuzz -i testcases/ -o findings/ aflbuild/afldemo
```
You have to run the above script first to run AFL and generate test cases for training

**Comment by zhtrb** [comment]
When I run the last command, I still find error:
`[-]  SYSTEM ERROR : connect() failed
    Stop location : setup_socket(), afl-fuzz.c:1379
       OS message : Connection refused
`
Am I right? I find some input sample in DEMO_DIR/testcase

**Comment by zhtrb** [comment]
> When I run the last command, I still find error:
> `[-] SYSTEM ERROR : connect() failed Stop location : setup_socket(), afl-fuzz.c:1379 OS message : Connection refused `
> Am I right? I find some input sample in DEMO_DIR/testcase

But these sample don't change.

**Comment by zhtrb** [comment]
can you tell me you package edition? I guess the problem in my computer is caused by the environment.

**Comment by duytai** [comment]
@zhtrb sorry for my late response. You should run two commands in two separated tabs:
```bash
./fuzz_me # it will create a socket server to serve request from AFL
./afl_gradient.sh # run modified AFL
```

**Comment by zhtrb** [comment]
@duytai Thanks for your reply. But my problem happened when run step.4 training. When I do the command 
`./fuzz_me coverage`
then there will be error.

**Comment by zhtrb** [comment]
I guess my error is because that there is no .cov file in my path
`def count(self):
        inputs, labels = [], [] 
        self.stats = { "shape": [0, 0], "offsets": [], "total": 0 }

        for f in list(glob.glob(self.options["queue"] + "/*")):
            data = load_file(f)
            self.stats["shape"][0] = len(data) if len(data) > self.stats["shape"][0] else self.stats["shape"][0]

        assert self.stats["shape"][0] > 0
        # read files from queue
        queue = list(glob.glob(self.options["queue"] + "/*"))
        for idx, f in enumerate(queue):
            print("+ Progress %d/%d" % (idx + 1, len(queue)))
            #  TODO: when flip is good
            #  flipped = flip_bytes(load_file(f))
            #  for idx, data in enumerate(flipped):
                #  print("+ Flipped %d/%d" % (idx + 1, len(flipped)))
            process = self.execute(data)
            **trace_bits = self.parse_santizer_coverage(dir_path=".cov", pid=process.pid)**
            # write input and label to file
            inputs.append(data)
            labels.append(trace_bits)
            self.stats["offsets"] += list(trace_bits.keys())
            self.stats["offsets"] = sorted(list(set(self.stats["offsets"])))
        # update shape
        self.stats["shape"][1] = len(self.stats["offsets"])
        assert self.stats["shape"][1] > 0

        # write to disk
        for idx in range(len(inputs)):
            label = self.reduce_label(labels[idx])
            input = inputs[idx]
            save_file("%s/I.%d.%d.bin" % (self.options["data_dir"], os.getpid(), idx), input)
            save_file("%s/L.%d.%d.bin" % (self.options["data_dir"], os.getpid(), idx), label)
        # save uniq offset
        self.stats["total"] = len(inputs)
        json_dump("%s/stats.json" % (self.options["data_dir"]), self.stats)
        print(self.stats)`
so how can I get such files?

**Comment by zhtrb** [comment]
`trace_bits = self.parse_santizer_coverage(dir_path=".cov", pid=process.pid)`
I guess my error is because that there is no .cov file in my path.
It's a line from function count, line 65 in coverage.py.
So if that's mean I should add some files in some directory? I cannot find the path ".cov/*.%d.sancov"

**Comment by duytai** [comment]
@zhtrb I updated the source code. The architecture is now simpler and much easier to understand. Can you try the project again. If there is no problem, can we have a discussion to push this project forward

**Comment by zhtrb** [comment]
@duytai Okay. I'm sorry about that I have to do other jobs which my boss ask me to do in the company these days and took a long time to learn rust and pytorch. I haven't finished it. I'll try my best to learn as soon as possible.

**Comment by duytai** [comment]
@zhtrb no worries, ping me when you are free of your company tasks
