### ISSUE TITLE
Makefile problem

### ISSUE THREAD

**Issue by peilinfeng** [duytai/sNeu#6]
After I finished step 2, how do I use "sneu" command? Should I use make in the build folder? If it is, the Makefile has some errors. How do I fix it? Thank you .

**Comment by duytai** [comment]
Hi @peilinfeng, the source code is outdated. I will update it whenever i finish the evaluation (comparing with other tools). For now, you can try a prototype at this: https://github.com/duytai/rust-fuzzer

**Comment by peilinfeng** [comment]
@duytai Thank you.
